### ISSUE TITLE
Update derive_var_chg and derive_var_analysis_ratio functions

### ISSUE THREAD

**Issue by ap765541** [pharmaverse/admiralvaccine#143]
### Background Information

To add an additional argument that allows the user to apply a rounding to the results (CHG and R2BASE)

### Definition of Done

Argument added

**Comment by federicobaratin** [comment]
Hi Ben!
Yes, I will provide more info (also in the issue boxes) :)
During the ADIS review from JJ and Pfizer, we discussed that it would be interesting to add a new argument for the functions mentioned: a sort of rounding argument that allows the user to derive the variables with n decimals.
For example, 2.03 instead of 2.0333333.
I think that it could be done also in a later step maybe with a mutate, but we were wondering if it could be possible to derive it directly from the functions.
Thanks
