### ISSUE TITLE
Remove metatools dependency

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralvaccine#246]
{metatools} is currently an "Imports:" dependency of admiralvaccine. Not all companies choose to use {metatools}, so we actively try to avoid making this a dependency in the open source admiral packages. 

It is only being used to combine suppqual domains (`combine_supp()`), which could equally just be a step companies take prior to using your package/templates, as this would be then more consistent with all other admiral packages.

FYI @ahasoplakus

**Comment by rossfarrugia** [comment]
See latest discussions at https://github.com/pharmaverse/pharmaversesdtm/issues/112 which might impact the action taken here

**Comment by ahasoplakus** [comment]
Thanks @rossfarrugia @statasaurus ! Based on the discussion at https://github.com/pharmaverse/pharmaversesdtm/issues/112, I think we agree on keeping the same approach as {admiralonco} i.e. adding {metatools} to `Suggests` instead of `Imports` and also fixing the {supp_xx_vaccine} data sets in {pharmaversesdtm} that would resolve the issue in {metatools} as @statasaurus  mentioned above. For the change in {pharmaversesdtm} as @manciniedoardo mentioned "it might be good to wait to make this change and coordinate releases so that we don’t have any periods where test data is unavailable"
